// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMnpgTZmJS0RvwOM6hRmFE8HnSXMglSQE',
    appId: '1:121151222216:web:d587c5b3bc9aac1efa50fd',
    messagingSenderId: '121151222216',
    projectId: 'mis-turnos-app-cac3c',
    authDomain: 'mis-turnos-app-cac3c.firebaseapp.com',
    storageBucket: 'mis-turnos-app-cac3c.firebasestorage.app',
    measurementId: 'G-5N8GG6J1Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBynjE1Ppe5kcsSPeDbEElhlhOX8qKmick',
    appId: '1:121151222216:android:e175d2098cb16c5efa50fd',
    messagingSenderId: '121151222216',
    projectId: 'mis-turnos-app-cac3c',
    storageBucket: 'mis-turnos-app-cac3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp8xICXm_mBh1r1BVw2GgqZ04LjKDDf60',
    appId: '1:121151222216:ios:d4dd55fe1cda6b32fa50fd',
    messagingSenderId: '121151222216',
    projectId: 'mis-turnos-app-cac3c',
    storageBucket: 'mis-turnos-app-cac3c.firebasestorage.app',
    iosBundleId: 'com.example.misTurnosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp8xICXm_mBh1r1BVw2GgqZ04LjKDDf60',
    appId: '1:121151222216:ios:d4dd55fe1cda6b32fa50fd',
    messagingSenderId: '121151222216',
    projectId: 'mis-turnos-app-cac3c',
    storageBucket: 'mis-turnos-app-cac3c.firebasestorage.app',
    iosBundleId: 'com.example.misTurnosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMnpgTZmJS0RvwOM6hRmFE8HnSXMglSQE',
    appId: '1:121151222216:web:2962066d84cabf0afa50fd',
    messagingSenderId: '121151222216',
    projectId: 'mis-turnos-app-cac3c',
    authDomain: 'mis-turnos-app-cac3c.firebaseapp.com',
    storageBucket: 'mis-turnos-app-cac3c.firebasestorage.app',
    measurementId: 'G-5XMML81DQS',
  );
}
